/**
 * iOS home-screen widget target — the Apple half of the widgets feature.
 *
 * Three small launcher widgets (add expense, scan receipt, voice) live in this
 * one WidgetKit extension, vended together from the WidgetBundle in index.swift.
 * They hold no data and share no App Group: each is a pure shortcut whose tap
 * opens the app at a deep link (`waves:///…`) the app already routes. The
 * Android sibling is generated by plugins/withWavesWidgets.js.
 *
 * @type {import('@bacons/apple-targets/app.plugin').Config}
 */
module.exports = {
  type: 'widget',
  name: 'WavesWidgets',
  // Brand purple. These $-prefixed keys feed the target's Info.plist
  // (WidgetBackground / accent); the SwiftUI tile paints its own literal of the
  // same colour (index.swift's wavesAccent), since Color("$…") can't read them.
  colors: {
    $accent: '#7A5AF8',
    $widgetBackground: '#7A5AF8',
  },
};
