/**
 * The Wear OS companion — a standalone `:wear` Gradle module.
 *
 * A thin Wear Compose app that sends quick-add / voice / request-recent intents
 * to the paired phone over the Wearable Data Layer and renders what the phone
 * relays back. All ledger logic stays on the phone (src/lib/watch/bridge.tsx);
 * the shared transport is the WavesWatch Expo module. The watchOS sibling lives
 * in targets/watch.
 *
 * `android/` is generated and gitignored, so the whole module is emitted here at
 * prebuild — its build.gradle, manifest, Compose sources and resources — and
 * `settings.gradle` is taught to `include ':wear'` (the same withSettingsGradle
 * hook withShortNativeBuildPath.js uses). The module is standalone (not embedded
 * via `wearApp`), so it builds and installs independently of the phone APK.
 *
 * UNVERIFIED: authored on Windows with no Android/Wear build. The Wear Compose /
 * Kotlin / AGP version matrix in particular must be reconciled against the
 * generated android/ on a real emulator build before trust.
 */

const fs = require('fs');
const path = require('path');
const {
  withSettingsGradle,
  withProjectBuildGradle,
  withDangerousMod,
} = require('expo/config-plugins');

const WEAR_PACKAGE = 'app.waves.wear';
const APPLICATION_ID = 'app.waves.wear';
const MARKER = 'waves:wear-module';
// Kotlin 2 needs the Compose compiler Gradle plugin; Expo's generated root
// build.gradle only ships kotlin-gradle-plugin. Pinned to the Kotlin the RN
// gradle plugin resolves (Expo SDK 57 → 2.2.x); bump alongside an SDK upgrade.
const COMPOSE_COMPILER_VERSION = '2.2.21';

// --- settings.gradle include --------------------------------------------------

/** Pure: append the `:wear` include once. Idempotent on the marker. */
function settingsWithInclude(contents) {
  if (contents.includes(MARKER)) return contents;
  return `${contents}\n// ${MARKER} — see apps/mobile/plugins/withWavesWear.js\ninclude ':wear'\n`;
}

function includeWearModule(config) {
  return withSettingsGradle(config, (cfg) => {
    cfg.modResults.contents = settingsWithInclude(cfg.modResults.contents);
    return cfg;
  });
}

/** Pure: add the Compose compiler plugin to the root buildscript classpath, once. */
function buildscriptWithCompose(contents) {
  if (contents.includes('compose-compiler-gradle-plugin')) return contents;
  return contents.replace(
    /classpath\((['"])org\.jetbrains\.kotlin:kotlin-gradle-plugin\1\)/,
    `$&\n        classpath('org.jetbrains.kotlin:compose-compiler-gradle-plugin:${COMPOSE_COMPILER_VERSION}')`,
  );
}

function addComposeClasspath(config) {
  return withProjectBuildGradle(config, (cfg) => {
    cfg.modResults.contents = buildscriptWithCompose(cfg.modResults.contents);
    return cfg;
  });
}

// --- emitted module files -----------------------------------------------------

const buildGradle = `// ${MARKER} — generated by plugins/withWavesWear.js; do not edit under android/.
apply plugin: "com.android.application"
apply plugin: "org.jetbrains.kotlin.android"
apply plugin: "org.jetbrains.kotlin.plugin.compose"

android {
    namespace "${WEAR_PACKAGE}"
    compileSdk rootProject.ext.compileSdkVersion

    defaultConfig {
        applicationId "${APPLICATION_ID}"
        minSdkVersion 30
        // Pinned to 34, not the app's target: Wear OS 5 (API 35+) makes the
        // reduce_motion setting that wear-compose-navigation reads readable only
        // to apps targeting <= 34, so a higher target crashes on launch with a
        // SecurityException. Verified on a Wear OS 5 emulator.
        targetSdkVersion 34
        versionCode 1
        versionName "1.0"
    }

    buildFeatures {
        compose true
    }

    kotlinOptions {
        jvmTarget = "17"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    implementation platform("androidx.compose:compose-bom:2024.09.00")
    implementation "androidx.compose.runtime:runtime"
    implementation "androidx.compose.foundation:foundation"
    implementation "androidx.activity:activity-compose:1.9.2"
    implementation "androidx.wear.compose:compose-material:1.4.0"
    implementation "androidx.wear.compose:compose-foundation:1.4.0"
    implementation "androidx.wear.compose:compose-navigation:1.4.0"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.8.1"
    implementation "com.google.android.gms:play-services-wearable:18.2.0"
}
`;

const manifest = `<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android">

    <uses-feature android:name="android.hardware.type.watch" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />

    <application
        android:allowBackup="false"
        android:label="Waves"
        android:supportsRtl="true"
        android:theme="@android:style/Theme.DeviceDefault">

        <uses-library android:name="com.google.android.wearable" android:required="true" />
        <meta-data android:name="com.google.android.wearable.standalone" android:value="true" />

        <activity
            android:name=".MainActivity"
            android:exported="true"
            android:label="Waves">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>

        <!-- Inbound relay from the phone (recent / settings / ack). -->
        <service
            android:name=".PhoneListenerService"
            android:exported="true">
            <intent-filter>
                <action android:name="com.google.android.gms.wearable.MESSAGE_RECEIVED" />
                <data android:scheme="wear" android:host="*" android:pathPrefix="/waves" />
            </intent-filter>
        </service>
    </application>
</manifest>
`;

const relayKt = `package ${WEAR_PACKAGE}

import android.content.Context
import com.google.android.gms.tasks.Tasks
import com.google.android.gms.wearable.Wearable
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import org.json.JSONObject
import java.util.UUID
import java.util.concurrent.TimeUnit

/** A recent-expense row the phone relayed. */
data class RecentItem(
    val title: String,
    val subtitle: String,
    val amountText: String,
    val whenText: String,
)

/**
 * The Wear end of the relay. A process-wide holder the UI observes and the
 * listener service writes to. Messages match @waves/core's relay contract.
 */
object WearRelay {
    const val PATH = "/waves"

    private val _recent = MutableStateFlow<List<RecentItem>>(emptyList())
    val recent: StateFlow<List<RecentItem>> = _recent

    private val _recentCount = MutableStateFlow(5)
    val recentCount: StateFlow<Int> = _recentCount

    // The currency a quick-add is booked in, relayed from the phone's default.
    private val _currency = MutableStateFlow("USD")
    val currency: StateFlow<String> = _currency

    /** Called by PhoneListenerService for every inbound message. Fails closed on
     *  a malformed or version-skewed payload rather than crashing the binder. */
    fun onMessage(json: String) {
        val obj = try {
            JSONObject(json)
        } catch (e: Exception) {
            return
        }
        when (obj.optString("t")) {
            "recent" -> {
                val arr = obj.optJSONArray("items") ?: return
                val list = ArrayList<RecentItem>(arr.length())
                for (i in 0 until arr.length()) {
                    val it = arr.optJSONObject(i) ?: continue
                    list.add(
                        RecentItem(
                            it.optString("title"),
                            it.optString("subtitle"),
                            it.optString("amountText"),
                            it.optString("whenText"),
                        )
                    )
                }
                _recent.value = list
            }
            "settings" -> {
                _recentCount.value = obj.optInt("recentCount", _recentCount.value)
                obj.optString("currency").takeIf { it.isNotEmpty() }?.let { _currency.value = it }
            }
            else -> {}
        }
    }

    private suspend fun send(context: Context, message: JSONObject) {
        withContext(Dispatchers.IO) {
            try {
                val bytes = message.toString().toByteArray(Charsets.UTF_8)
                // Bounded so a node lookup that never resolves can't pin an IO
                // thread; a failed/timed-out send just shows no update on the watch.
                val nodes = Tasks.await(
                    Wearable.getNodeClient(context).connectedNodes,
                    10,
                    TimeUnit.SECONDS,
                )
                val client = Wearable.getMessageClient(context)
                for (node in nodes) {
                    client.sendMessage(node.id, PATH, bytes)
                }
            } catch (e: Exception) {
                // Swallowed on purpose — the Data Layer is best-effort here.
            }
        }
    }

    // Matches @waves/core's WATCH_RELAY_VERSION.
    private const val RELAY_VERSION = 1

    fun requestRecent(context: Context, scope: CoroutineScope) {
        scope.launch {
            send(
                context,
                JSONObject().put("t", "requestRecent").put("version", RELAY_VERSION)
                    .put("count", _recentCount.value),
            )
        }
    }

    fun quickAdd(
        context: Context,
        scope: CoroutineScope,
        amountMinor: Long,
        currency: String,
        note: String,
    ) {
        scope.launch {
            send(
                context,
                // A stable id per intent so a transport retry is idempotent on the phone.
                JSONObject().put("t", "quickAdd").put("version", RELAY_VERSION)
                    .put("id", UUID.randomUUID().toString())
                    .put("amountMinor", amountMinor.toString())
                    .put("currency", currency).put("note", note),
            )
        }
    }

    fun voiceAdd(context: Context, scope: CoroutineScope, transcript: String) {
        scope.launch {
            send(
                context,
                JSONObject().put("t", "voiceAdd").put("version", RELAY_VERSION)
                    .put("id", UUID.randomUUID().toString()).put("transcript", transcript),
            )
        }
    }
}
`;

const listenerKt = `package ${WEAR_PACKAGE}

import com.google.android.gms.wearable.MessageEvent
import com.google.android.gms.wearable.WearableListenerService

/** Receives the phone's relay messages and hands them to WearRelay. */
class PhoneListenerService : WearableListenerService() {
    override fun onMessageReceived(event: MessageEvent) {
        if (event.path != WearRelay.PATH) return
        WearRelay.onMessage(String(event.data, Charsets.UTF_8))
    }
}
`;

const mainActivityKt = `package ${WEAR_PACKAGE}

import android.app.Activity
import android.content.Intent
import android.os.Bundle
import android.speech.RecognizerIntent
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.runtime.Composable
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.unit.dp
import androidx.navigation.NavHostController
import androidx.wear.compose.material.Button
import androidx.wear.compose.material.Chip
import androidx.wear.compose.material.ChipDefaults
import androidx.wear.compose.material.MaterialTheme
import androidx.wear.compose.material.Stepper
import androidx.wear.compose.material.StepperDefaults
import androidx.wear.compose.material.Text
import androidx.wear.compose.foundation.lazy.ScalingLazyColumn
import androidx.wear.compose.foundation.lazy.items
import androidx.wear.compose.navigation.SwipeDismissableNavHost
import androidx.wear.compose.navigation.composable
import androidx.wear.compose.navigation.rememberSwipeDismissableNavController

class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent { WearApp() }
    }
}

@Composable
fun WearApp() {
    val nav: NavHostController = rememberSwipeDismissableNavController()
    MaterialTheme {
        SwipeDismissableNavHost(navController = nav, startDestination = "home") {
            composable("home") { HomeScreen(nav) }
            composable("add") { QuickAddScreen(nav) }
            composable("recent") { RecentScreen() }
        }
    }
}

@Composable
fun HomeScreen(nav: NavHostController) {
    val context = LocalContext.current
    val scope = rememberCoroutineScope()

    val voiceLauncher = androidx.activity.compose.rememberLauncherForActivityResult(
        ActivityResultContracts.StartActivityForResult()
    ) { result ->
        if (result.resultCode == Activity.RESULT_OK) {
            val spoken = result.data
                ?.getStringArrayListExtra(RecognizerIntent.EXTRA_RESULTS)
                ?.firstOrNull()
                ?.trim()
                .orEmpty()
            if (spoken.isNotEmpty()) WearRelay.voiceAdd(context, scope, spoken)
        }
    }

    ScalingLazyColumn(modifier = Modifier.fillMaxSize()) {
        item { Text("Waves") }
        item {
            Chip(
                modifier = Modifier.fillMaxWidth(),
                label = { Text("Speak") },
                onClick = {
                    val intent = Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH).apply {
                        putExtra(
                            RecognizerIntent.EXTRA_LANGUAGE_MODEL,
                            RecognizerIntent.LANGUAGE_MODEL_FREE_FORM,
                        )
                        putExtra(RecognizerIntent.EXTRA_PROMPT, "Say what you spent")
                    }
                    voiceLauncher.launch(intent)
                },
                colors = ChipDefaults.primaryChipColors(),
            )
        }
        item {
            Chip(
                modifier = Modifier.fillMaxWidth(),
                label = { Text("Add") },
                onClick = { nav.navigate("add") },
                colors = ChipDefaults.secondaryChipColors(),
            )
        }
        item {
            Chip(
                modifier = Modifier.fillMaxWidth(),
                label = { Text("Recent") },
                onClick = {
                    WearRelay.requestRecent(context, scope)
                    nav.navigate("recent")
                },
                colors = ChipDefaults.secondaryChipColors(),
            )
        }
    }
}

@Composable
fun QuickAddScreen(nav: NavHostController) {
    val context = LocalContext.current
    val scope = rememberCoroutineScope()
    val currency by WearRelay.currency.collectAsState()
    // Whole units on the crown/stepper; converted to minor units on send.
    var amount by remember { mutableStateOf(0) }

    Column(
        modifier = Modifier.fillMaxSize().padding(8.dp),
        verticalArrangement = Arrangement.spacedBy(6.dp),
    ) {
        Stepper(
            value = amount,
            onValueChange = { amount = it },
            valueProgression = 0..100000 step 10,
            decreaseIcon = { Text("-") },
            increaseIcon = { Text("+") },
            modifier = Modifier.weight(1f),
        ) {
            Text("$currency $amount")
        }
        Button(
            onClick = {
                if (amount > 0) {
                    WearRelay.quickAdd(context, scope, amount.toLong() * 100, currency, "")
                    nav.popBackStack()
                }
            },
            modifier = Modifier.fillMaxWidth(),
        ) {
            Text("Add")
        }
    }
}

@Composable
fun RecentScreen() {
    val context = LocalContext.current
    val scope = rememberCoroutineScope()
    val recent by WearRelay.recent.collectAsState()

    androidx.compose.runtime.LaunchedEffect(Unit) { WearRelay.requestRecent(context, scope) }

    ScalingLazyColumn(modifier = Modifier.fillMaxSize()) {
        item { Text("Recent") }
        if (recent.isEmpty()) {
            item { Text("Nothing yet") }
        } else {
            items(recent) { row ->
                Column(
                    modifier = Modifier.fillMaxWidth().padding(vertical = 4.dp),
                    verticalArrangement = Arrangement.spacedBy(2.dp),
                ) {
                    Text(row.title, maxLines = 1)
                    Text(
                        row.amountText + "  ·  " + row.whenText,
                        style = MaterialTheme.typography.caption2,
                    )
                }
            }
        }
    }
}
`;

// --- write to the generated module -------------------------------------------

function writeFile(filePath, contents) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, contents);
}

function writeWearModule(projectRoot) {
  const wear = path.join(projectRoot, 'android', 'wear');
  const pkgDir = path.join(wear, 'src', 'main', 'java', ...WEAR_PACKAGE.split('.'));

  writeFile(path.join(wear, 'build.gradle'), buildGradle);
  writeFile(path.join(wear, 'src', 'main', 'AndroidManifest.xml'), manifest);
  writeFile(path.join(pkgDir, 'WearRelay.kt'), relayKt);
  writeFile(path.join(pkgDir, 'PhoneListenerService.kt'), listenerKt);
  writeFile(path.join(pkgDir, 'MainActivity.kt'), mainActivityKt);
}

module.exports = function withWavesWear(config) {
  config = includeWearModule(config);
  config = addComposeClasspath(config);
  config = withDangerousMod(config, [
    'android',
    (cfg) => {
      writeWearModule(cfg.modRequest.projectRoot);
      return cfg;
    },
  ]);
  return config;
};

module.exports._internals = {
  WEAR_PACKAGE,
  APPLICATION_ID,
  MARKER,
  buildGradle,
  manifest,
  settingsWithInclude,
  buildscriptWithCompose,
  writeWearModule,
};
